Controllers/CourseController.cs
using AutoMapper;
using BusinessLogicLayer.Interfaces;
using DataAccessLayer.Etities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using presentationLayer.ViewModels;
using pusinessLogicLayer.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace presentationLayer.Controllers
{
    [Authorize]
    public class CourseController : Controller
    {
        private readonly IMapper _mapper;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUnitOfWork _unitOfWork;

        public CourseController(IMapper mapper,
            UserManager<ApplicationUser> userManager, IUnitOfWork unitOfWork)
        {
            _mapper = mapper;
            _userManager = userManager;
            _unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var courses = Enumerable.Empty<Course>();
            if (user.UserRoleName != "Admin")
            {
                var instructor = _unitOfWork._instructorRepository.GetInstructorByEmail(user.Email);
                courses = await _unitOfWork._courseRepository.GetCoursesByInstructor(instructor.Id);
            }
            else
                courses = await _unitOfWork._courseRepository.GetAll();

            var mappedCourses =
                _mapper.Map<IEnumerable<Course>, IEnumerable<CourseModel>>(courses);
            return View(mappedCourses);
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(CourseModel courseModel)
        {
            if (ModelState.IsValid)
            {
                var mappedCourse = _mapper.Map<CourseModel, Course>(courseModel);
                await _unitOfWork._courseRepository.Add(mappedCourse);
                return RedirectToAction(nameof(Index));
            }
            return View(courseModel);
        }

        public async Task<IActionResult> Details(int? id, string viewName = "Details")
        {
            if(id == null)
            {
                return NotFound();
            }
            var myCourse =await _unitOfWork._courseRepository.Get(id.Value);
            if(myCourse == null)
            {
                return NotFound();
            }
            var mappedCourse = _mapper.Map<Course, CourseModel>(myCourse);
            return View(viewName, mappedCourse);
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            return await Details(id, "Edit");
            //if (id == null)
            //{
            //    return NotFound();
            //}
            //var c = _CourseRepository.Get(id.Value);
            //if (c == null)
            //{
            //    return NotFound();
            //}
            //return View(c);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit([FromRoute]int id, CourseModel c)
        {
            if(id != c.Id)
            {
                return BadRequest();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    var mappedCourse = _mapper.Map<CourseModel, Course>(c);
                    await _unitOfWork._courseRepository.Update(mappedCourse);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception)
                {
                    return View(c);
                }
            }
            return View(c);
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            return await Details(id, "Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete([FromRoute] int id, CourseModel c)
        {
            if (id != c.Id)
            {
                return BadRequest();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    var mappedCourse = _mapper.Map<CourseModel, Course>(c);
                    await _unitOfWork._courseRepository.Delete(mappedCourse);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception)
                {
                    return View(c);
                }
            }
            return View(c);
        }

    }
}

Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace presentationLayer.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleController(RoleManager<IdentityRole> RoleManager)
        {
            _roleManager = RoleManager;
        }
        public IActionResult Index()
        {
            var roles = _roleManager.Roles;

            return View(roles);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole identityRole)
        {
            if (ModelState.IsValid)
            {
                await _roleManager.CreateAsync(identityRole);
                return RedirectToAction(nameof(Index));
            }

            return View(identityRole);
        }

        public async Task<IActionResult> Details(string id, string viewName = "Details")
        {
            if (id == null)
                return NotFound();

            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
                return NotFound();

            return View(viewName, role);
        }

        public async Task<IActionResult> Edit(string id)
        {

            return await Details(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string id, IdentityRole identityRole)
        {
            if (id != identityRole.Id)
            {
                return BadRequest();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    var role = await _roleManager.FindByIdAsync(id);
                    if (role.Name == "Admin" || role.Name == "User")
                        return View(identityRole);
                    role.Id = identityRole.Id;
                    role.Name = identityRole.Name;
                    await _roleManager.UpdateAsync(role);

                    return RedirectToAction(nameof(Index));
                }
                catch (Exception)
                {
                    return View(identityRole);
                }
            }
            return View(identityRole);
        }

        public async Task<IActionResult> Delete(string id)
        {
            return await Details(id, "Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] string id, IdentityRole identityRole)
        {
            if (id != identityRole.Id)
            {
                return BadRequest();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    var role = await _roleManager.FindByIdAsync(id);
                    if (role.Name == "Admin" || role.Name == "User")
                        return View(identityRole);
                    await _roleManager.DeleteAsync(role);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception)
                {
                    return View(identityRole);
                }
            }
            return View(identityRole);
        }
    }
}

Controllers/SessionController.cs
using AutoMapper;
using BusinessLogicLayer.BllHelpers;
using BusinessLogicLayer.Interfaces;
using DataAccessLayer.Etities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using presentationLayer.Helpers;
using presentationLayer.ViewModels;
using pusinessLogicLayer.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace presentationLayer.Controllers
{
    [Authorize]
    public class SessionController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _unitOfWork;

        public SessionController(IMapper mapper, IUnitOfWork unitOfWork)
        {
            _mapper = mapper;
            _unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> Index()
        {
            var sessions = await _unitOfWork._sessionRepository.GetAll();
            var mappedSessions =
                _mapper.Map<IEnumerable<Session>, IEnumerable<SessionModel>>(sessions);
            return View(mappedSessions);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(SessionModel sessionModel)
        {
            var sessionCourse = await _unitOfWork._courseRepository.Get(sessionModel.CourseId);
            sessionModel.InstructorId = sessionCourse.InstructorId;
            if (ModelState.IsValid)
            {
                var mappedSession = _mapper.Map<SessionModel, Session>(sessionModel);
                await _unitOfWork._sessionRepository.Add(mappedSession);
                // just for Ex.
                var sessionStudents = await _unitOfWork._studentRepository.GetAll();
                var studentIds = sessionStudents.Select(ss => ss.Id);
                var sessionId = mappedSession.Id;
                var sessionJson = new SessionJson
                {
                    SessionId = sessionId,
                    Students = new List<int>()
                };

                foreach (var studentId in studentIds)
                {
                    var studentJson = studentId;

                    sessionJson.Students.Add(studentJson);
                }

                var sessionJsonString = JsonSerializer.Serialize(sessionJson);
                await _unitOfWork._studentRepository.AddStudentsToSession(sessionJsonString);
                //int sessionId, int[] studentIds
                //string json = @"{ ""SessionId"": 1, ""StudentIds"": [1,2,3] }";
                //await studentRepository.AddSessionToStudentsAsync(json);
                //var sessionJson = JsonSerializer.Serialize(new
                //{
                //    sessionId = mappedSession.Id,
                //    students = sessionStudents
                //});
                //////////////
                return RedirectToAction(nameof(Index));
            }
            return View(sessionModel);
        }

        public async Task<IActionResult> Details(int? id, string viewName = "Details")
        {
            if (id == null)
            {
                return NotFound();
            }
            var mySession = await _unitOfWork._sessionRepository.Get(id.Value);
            if (mySession == null)
            {
                return NotFound();
            }
            var mappedSession = _mapper.Map<Session, SessionModel>(mySession);
            mappedSession.Course = await _unitOfWork._courseRepository.Get(mappedSession.CourseId);
            mappedSession.Students = await _unitOfWork._studentRepository.GetStudentsBySessionAsync(mySession);

            return View(viewName, mappedSession);
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            return await Details(id, "Edit");
            //if (id == null)
            //{
            //    return NotFound();
            //}
            //var c = _SessionRepository.Get(id.Value);
            //if (c == null)
            //{
            //    return NotFound();
            //}
            //return View(c);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit([FromRoute] int id, SessionModel c)
        {
            if (id != c.Id)
            {
                return BadRequest();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    var session = await _unitOfWork._sessionRepository.Get(id);
                    c.Instructor = session.Instructor; 
                    c.InstructorId = session.InstructorId; 
                    var mappedSession = _mapper.Map<SessionModel, Session>(c);
                    await _unitOfWork._sessionRepository.Update(mappedSession);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    return View(c);
                }
            }
            return View(c);
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            return await Details(id, "Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete([FromRoute] int id, SessionModel sessionModel)
        {
            ModelState.Clear();
            var c = await _unitOfWork._courseRepository.Get(sessionModel.CourseId);
            sessionModel.Course = c;
            sessionModel.Course.Code = c.Code;
            sessionModel.InstructorId = c.InstructorId; 
            sessionModel.Instructor = c.Instructor; 
            if (id != sessionModel.Id)
            {
                return BadRequest();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    var mappedSession = _mapper.Map<SessionModel, Session>(sessionModel);
                    await _unitOfWork._sessionRepository.Delete(mappedSession);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    return View(sessionModel);
                }
            }
            else
            {
            //    // Create a list to hold the errors
            //    var errors = new List<string>();

            //    // Iterate over the ModelState.Values collection
            //    foreach (var state in ModelState.Values)
            //    {
            //        if (state.Errors != null && state.Errors.Count > 0)
            //        {
            //            // Iterate over the Errors collection of the ModelStateEntry object
            //            foreach (var error in state.Errors)
            //            {
            //                // Add the error message to the list
            //                errors.Add(error.ErrorMessage);
            //            }
            //        }
            //    }
            }
            return View(sessionModel);
        }

    }
}


Views/Shared/TableBottons.cshtml
@model int

<td><a asp-action="Details" asp-route-id="@Model" class="btn btn-warning">Details</a></td>
@if (User.IsInRole("Admin"))
 {
    <td><a asp-action="Edit" asp-route-id="@Model" class="btn btn-info">update</a></td>
    <td><a asp-action="Delete" asp-route-id="@Model" class="btn btn-danger">Delete</a></td>
 }




Views/Shared/_AuthLayout.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
    <title>Creative Colorlib @ViewData["Title"] Form</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- Custom Theme files -->
    <link href="~/css/AuthStyle.css" rel="stylesheet" />
    <!-- //Custom Theme files -->
    <!-- web font -->
    <link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
    <!-- //web font -->
</head>
<body>
    <!-- main -->
    <div class="main-w3layouts wrapper">
        <h1>@ViewData["Title"] Form</h1>
        @RenderBody()
        <!-- copyright -->
        <div class="colorlibcopy-agile">
            <p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
        </div>
        <!-- //copyright -->
        <ul class="colorlib-bubbles">
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
        </ul>
    </div>
    <!-- //main -->

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - presentationLayer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">presentationLayer</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Session" asp-action="Index">Sessions</a>
                        </li>
                       @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Instructor" asp-action="Index">Instructors</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                            </li>
                        }

                    </ul>
                </div>
                <a class="nav-link text-dark float-right btn" asp-controller="Account" asp-action="LogOut">Log Out</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - presentationLayer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>